package md2hyper;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class HTMLGenerator {

    public void generate(Document document, Path outputPath) {
        if (document == null || outputPath == null) {
            throw new IllegalArgumentException("Document or output path cannot be null.");
        }

        try (BufferedWriter writer = Files.newBufferedWriter(outputPath)) {
            System.out.println("Writing HTML to " + outputPath.toAbsolutePath());

            writer.write("<!DOCTYPE HTML>");
            writer.newLine();
            writer.write("<!-- GENERATED BY md2hyper -->");
            writer.write("<html>");
            writer.newLine();
            writer.write("<body>");
            writer.newLine();

            for (Document.Element element : document.getElements()) {
                writer.write(renderElement(element));
                writer.newLine();
            }

            writer.write("</body>");
            writer.newLine();
            writer.write("</html>");
            writer.newLine();


        } catch (IOException e) {
            System.err.println("An IOException has been caught.");
            e.printStackTrace();
        }
    }

    private String renderElement(Document.Element element) {
        String type = element.getType().toLowerCase();
        String content = escapeHTML(element.getContent());

        return switch (type) {
            case "h1" -> "<h1>" + content + "</h1>";
            case "h2" -> "<h2>" + content + "</h2>";
            case "p"  -> "<p>"  + content + "</p>";
            case "div"-> "<div>" + content + "</div>";
            case "span"-> "<span>" + content + "</span>";
            default   -> "<!-- Unknown element type: " + type + " -->";
        };
    }

    private String escapeHTML(String in) {
        return in
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;");
    }
}